# Generated by Django 4.2.16 on 2024-12-02 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acudiente', '0001_initial'),
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegracionContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoIntegracion', models.BigIntegerField()),
                ('fechaGeneracion', models.DateField(auto_now_add=True)),
                ('paz_y_salvo', models.BooleanField(default=False)),
                ('acudiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acudiente.acudiente')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante')),
            ],
        ),
    ]
