# Generated by Django 3.2.6 on 2024-10-07 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '0001_initial'),
        ('acudiente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoPago', models.BigIntegerField()),
                ('monto', models.BigIntegerField()),
                ('fechaPago', models.DateField()),
                ('acudiente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acudiente.acudiente')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='estudiante.estudiante')),
            ],
        ),
    ]
